// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	context "context"

	symo "github.com/anfilat/final-stats/internal/symo"
	mock "github.com/stretchr/testify/mock"
)

// CPU is an autogenerated mock type for the CPU type
type CPU struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, action
func (_m *CPU) Execute(ctx context.Context, action symo.MetricCommand) (*symo.CPUData, error) {
	ret := _m.Called(ctx, action)

	var r0 *symo.CPUData
	if rf, ok := ret.Get(0).(func(context.Context, symo.MetricCommand) *symo.CPUData); ok {
		r0 = rf(ctx, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*symo.CPUData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, symo.MetricCommand) error); ok {
		r1 = rf(ctx, action)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
