// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	context "context"

	symo "github.com/anfilat/final-stats/internal/symo"
	mock "github.com/stretchr/testify/mock"
)

// LoadDisks is an autogenerated mock type for the LoadDisks type
type LoadDisks struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, action
func (_m *LoadDisks) Execute(ctx context.Context, action symo.MetricCommand) (symo.LoadDisksData, error) {
	ret := _m.Called(ctx, action)

	var r0 symo.LoadDisksData
	if rf, ok := ret.Get(0).(func(context.Context, symo.MetricCommand) symo.LoadDisksData); ok {
		r0 = rf(ctx, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(symo.LoadDisksData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, symo.MetricCommand) error); ok {
		r1 = rf(ctx, action)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
